# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  workflow_dispatch:

jobs:
  create_commit:
    runs-on: ubuntu-latest 
    permissions:
      checks: write 
    steps:
      - run: |
          echo ${GITHUB_RUN_ID}
      - name: REST API
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/jobs/${GITHUB_JOB} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' 
          
      - name: REST API 2 
        run: |
          curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/check-runs/${GITHUB_RUN_ID} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json'
